·server:
  port: 8080
# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_rental_db
    username: root
    password: Atos.1912
mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml






