·server:
  port: 8082
# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_rental_db
    username: root
    password: password
mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml






